
dataset: drugbank

# download-username: vincent.emonet@maastrichtuniversity.nl
# download-password: maasitest12

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: http://graphdb:7200/repositories/test/statements
sparql_tmp_service_url: "http://localhost:7200/repositories/test"
sparql_tmp_triplestore_username: dba
sparql_tmp_triplestore_password: password

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/drugbank"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF

sparql_final_triplestore_url: http://graphdb:7200/repositories/test/statements
sparql_final_triplestore_username: dba
sparql_final_triplestore_password: password

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/drugbank


sparql_transform_queries_path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/datasets/drugbank/mappings/1
sparql_insert_metadata_path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/datasets/drugbank/metadata/1

config_dir:
  class: Directory
  path: .