## Transform XML

# Path to the input directory on your machine
dir_to_process:
  class: Directory
  path: ../../workspace/input/drugbank

# download-username: vincent.emonet@maastrichtuniversity.nl
# download-password: password

sparql_final_graph_uri: https://w3id.org/trek/graph/drugbank

# Final SPARQL endpoint to load the BioLink RDF
sparql_final_triplestore_url: "http://graphdb:7200/repositories/demo/statements"
# sparql_final_triplestore_url: "http://virtuoso:8890/sparql"
# sparql_final_triplestore_url: "http://blazegraph:8080/bigdata/sparql"

sparql_final_triplestore_username: "dba"
sparql_final_triplestore_password: "dba"

# tmp SPARQL endpoint to load generic RDF
sparql_tmp_service_url: "http://tmp-virtuoso:8890/sparql"
sparql_tmp_triplestore_url: "http://tmp-virtuoso:8890/sparql"
sparql_tmp_triplestore_username: dba
sparql_tmp_triplestore_password: dba

sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/xml2rdf"
tmp_triplestore_container_id: "d2s-cwl-workflows_tmp-virtuoso_1"
tmp_triplestore_load_dir: "/usr/local/virtuoso-opensource/var/lib/virtuoso/db"

sparql_transform_queries_path: "mapping"
sparql_insert_metadata_path: "metadata"

cwl_workflow_filename: "xml-virtuoso.cwl"

config_dir:
  class: Directory
  path: .

cwl_dir:
  class: Directory
  path: ../../d2s-cwl-workflows