
input_dir:
  class: Directory
  path: /data/d2s-workspace/input/drugbank

# download-username: vincent.emonet@maastrichtuniversity.nl
# download-password: maasitest12

# tmp RDF4J server SPARQL endpoint to load generic RDF
# sparql_tmp_triplestore_url: http://graphdb:7200/repositories/test/statements
sparql_tmp_triplestore_url: http://graphdb.dumontierlab.com/repositories/test-vincent
sparql_tmp_service_url: "http://localhost:7200/repositories/test-vincent"
sparql_tmp_triplestore_username: import_user
sparql_tmp_triplestore_password: test

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/xml2rdf"


# Final RDF4J server SPARQL endpoint to load the BioLink RDF
# sparql_final_triplestore_url: http://graphdb:7200/repositories/test/statements
sparql_final_triplestore_url: http://graphdb.dumontierlab.com/repositories/test-vincent
sparql_final_triplestore_username: import_user
sparql_final_triplestore_password: test

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/drugbank/calrissian

sparql_transform_queries_path: "mappings/1"
sparql_insert_metadata_path: "metadata/1"

cwl_workflow_filename: graphdb-workflow-xml.cwl

config_dir:
  class: Directory
  path: .

cwl_dir:
  class: Directory
  path: ../../d2s-cwl-workflows