version: "3"

services:

  virtuoso:
    image: tenforce/virtuoso
    restart: unless-stopped
    volumes:
      - /data/red-kg:/data
    ports:
      - 8890:8890
      - 1111:1111
    environment:
      - DBA_PASSWORD=dba
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=https://w3id.org/data2services/graph
    networks:
      - d2s-network

  drill:
    image: vemonet/apache-drill
    ports:
      - 8047:8047
      - 31010:31010
    tty: true
    volumes:
      - /data/red-kg:/data:ro
    networks:
      - d2s-network


  # graphdb:
  #   build: ./submodules/graphdb
  #   volumes:
  #     - /data/red-kg/graphdb:/opt/graphdb/home
  #     - /data/red-kg/graphdb-import:/root/graphdb-import
  #   ports:
  #     - 7200:7200
  #   networks:
  #     - d2s-network


  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - d2s-network

  # http://localhost:8889/bigdata/#splash
  # https://hub.docker.com/r/lyrasis/blazegraph
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    volumes:
      # - /data/red-kg/RWStore.properties:/RWStore.properties
      - /data/red-kg:/data
    ports:
      - 8889:8080
    # environment:
    #   - BLAZEGRAPH_UID=$BLAZEGRAPH_UID
    #   - BLAZEGRAPH_GID=$BLAZEGRAPH_GID
    networks:
      - d2s-network

networks:
  d2s-network:
    driver: bridge



# docker exec -it docker-compose_virtuoso_1 bash
# isql-v -U dba -P password
# ld_dir('output', '*.nq', 'http://test/');
# rdf_loader_run();

# One liner virtuoso bulk load:
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="ld_dir('/usr/local/virtuoso-opensource/var/lib/virtuoso/db/output', '*.nq', 'http://test/'); rdf_loader_run();"
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="ld_dir('output', '*.nq', 'http://test/'); rdf_loader_run();"

# Reset triplestore:
#docker exec -it docker-compose_virtuoso_1 isql-v -U dba -P password exec="RDF_GLOBAL_RESET ();"

# Try to load with RdfUpload
# docker run -it --rm --net docker-compose_d2s-network -v /data/red-kg/output:/data vemonet/rdf-upload -if "/data" -url "http://virtuoso:8890" -un "dba" -pw "password"

# sparql-operations works though
# docker run -it --net docker-compose_d2s-network --rm vemonet/data2services-sparql-operations -op select -sp "select distinct ?Concept where {[] a ?Concept} LIMIT 1000" -ep "http://virtuoso:8890/sparql"
