working_directory: /data/data2services-transform-biolink

dataset: eggnog

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"
sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/eggnog"

# RdfUpload params
sparql_triplestore_url: http://graphdb:7200
sparql_triplestore_repository: test

# Split params
split_property: https://w3id.org/data2services/model/Proteinids
split_class: https://w3id.org/data2services/data/input/eggnog/NOG.members.extract101.tsv
split_delimiter: ","
split_quote: '"'

# Execute SPARQL conversion queries
sparql_username: emonet
sparql_password: PASSWORD
sparql_output_graph_uri: https://w3id.org/data2services/graph/biolink/eggnog
sparql_service_url: "http://localhost:7200/repositories/test"
sparql_queries_path: /data/mapping/eggnog