
## For Tabular files workflows
dataset_to_process: "omop-drugbank"

sparql_final_graph_uri: "https://w3id.org/d2s/graph/omop-drugbank"

# Final SPARQL endpoint to load the BioLink RDF
# Add /statements for RDF4J server like GraphDB
# sparql_final_triplestore_url: "https://graphdb.dumontierlab.com/repositories/trek/statements"
sparql_final_triplestore_url: "http://graphdb:7200/repositories/trek/statements"

sparql_final_triplestore_username: "import_user"
sparql_final_triplestore_password: "dba"

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"

# Temporary triplestore (e.g. Virtuoso). TODO: improve
sparql_tmp_service_url: "http://tmp-virtuoso:8890/sparql"
# sparql_tmp_service_url: "http://blazegraph:8082/bigdata/sparql"

sparql_tmp_triplestore_url: "http://tmp-virtuoso:8890/sparql"
# sparql_tmp_triplestore_url: "http://blazegraph:8082/bigdata/sparql"
sparql_tmp_triplestore_username: "dba"
sparql_tmp_triplestore_password: "dba"

sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/autor2rml"
# sparql_tmp_graph_uri: "https://w3id.org/d2s/graph/omop-drugbank"

tmp_triplestore_container_id: "d2s-tmp-virtuoso"
tmp_triplestore_load_dir: "/usr/local/virtuoso-opensource/var/lib/virtuoso/db"

# Split params
# split_property: "https://w3id.org/biolink/vocab/has_participant"
# split_class: "https://w3id.org/biolink/vocab/GeneGrouping"
# split_delimiter: ","
# split_quote: '"'

sparql_transform_queries_path: "mapping"
sparql_insert_metadata_path: "metadata"

cwl_workflow_filename: "csv-virtuoso.cwl"

config_dir:
  class: Directory
  path: .

cwl_dir:
  class: Directory
  path: ../../d2s-core
