working-directory: /data/d2s-transform-template

#dataset: pubmed-sample
dataset: pubmed

# d2s-download params
# download-username: vincent.emonet@maastrichtuniversity.nl
# download-password: null

# tmp RDF4J server SPARQL endpoint to load generic RDF
#sparql-tmp-triplestore-url: http://graphdb:7200
sparql-tmp-triplestore-url: http://node000002.cluster.ids.unimaas.nl/
sparql-tmp-triplestore-repository: "test"
sparql-tmp-service-url: "repository:test"
sparql-tmp-triplestore-username: import_user
sparql-tmp-triplestore-password: test

sparql-tmp-graph-uri: "https://w3id.org/data2services/graph/xml2rdf/pubmed"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
#sparql-final-triplestore-url: http://graphdb:7200
sparql-final-triplestore-url: http://node000002.cluster.ids.unimaas.nl/
sparql-final-triplestore-repository: "test"
sparql-final-triplestore-username: import_user
sparql-final-triplestore-password: test

sparql-final-graph-uri: https://w3id.org/data2services/graph/biolink/pubmed

sparql-transform-queries-path: https://github.com/MaastrichtU-IDS/d2s-transform-template/tree/master/mapping/pubmed/transform/1
sparql-insert-metadata-path: https://github.com/MaastrichtU-IDS/d2s-transform-template/tree/master/mapping/pubmed/metadata/1

# Argo require to use the URL, but local volumes can be shared
# sparql-transform-queries-path: /data/mapping/pubmed/transform/1