working_directory: /data/d2s-transform-biolink
#dataset: pubmed-sample
dataset: pubmed

# d2s-download params
download_username: vincent.emonet@maastrichtuniversity.nl
download_password: PASSWORD

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: http://graphdb:7200
sparql_tmp_triplestore_repository: test
sparql_tmp_service_url: repository:test
sparql_tmp_triplestore_username: import_user
sparql_tmp_triplestore_password: PASSWORD

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/xml2rdf/pubmed"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
sparql_final_triplestore_url: http://graphdb:7200
sparql_final_triplestore_repository: "test"
sparql_final_triplestore_username: import_user
sparql_final_triplestore_password: PASSWORD

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/pubmed


sparql_transform_queries_path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/mapping/pubmed/transform/1
sparql_insert_metadata_path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/mapping/pubmed/metadata/1

# Run workflow
# cwl-runner --outdir output/pubmed d2s-cwl-workflows/workflows/workflow-xml.cwl support/config/config-transform-xml-pubmed.yml