working_directory: /data/data2services-transform-biolink

dataset: stitch

download_files: '[
  {
    baseUrl: "http://stitch.embl.de/download/",
    files: ["chemical_chemical.links.v5.0.tsv.gz", 
      "protein_chemical.links.detailed.v5.0/9606.protein_chemical.links.detailed.v5.0.tsv.gz"],
    splitColumns: ["Proteinids", "Drugids"],
    regexHtml: ".*(http.*\.ttl\.gz).*"
}]'

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"
sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/stitch"

# RdfUpload params
sparql_triplestore_url: http://graphdb:7200
sparql_triplestore_tmp_repository: test

# Execute SPARQL conversion queries
sparql_username: import_user
sparql_password: PASSWORD
sparql_output_graph_uri: https://w3id.org/data2services/graph/biolink/stitch
sparql_service_url: "http://localhost:7200/repositories/test"

sparql_transform_queries_path: /data/mapping/stitch/transform/1
sparql_insert_metadata_path: /data/mapping/stitch/metadata/1
