working_directory: /data/data2services-transform-biolink

dataset: pharmgkb

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"
#sparql_base_uri: "https://w3id.org/data2services/"
#autor2rml_column_header: "test1,test2,test3,test5"

# Split params
split_property: https://w3id.org/data2services/model/Pmids
split_class: https://w3id.org/data2services/data/input/pharmgkb/relationships_extract101.tsv
split_delimiter: ";"
split_quote: '"'

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: http://graphdb:7200
sparql_tmp_triplestore_repository: "test"
sparql_tmp_service_url: "repository:test"
sparql_tmp_triplestore_username: import_user
sparql_tmp_triplestore_password: PASSWORD

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/pharmgkb"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
sparql_final_triplestore_url: http://graphdb:7200
sparql_final_triplestore_repository: "test"
sparql_final_triplestore_username: import_user
sparql_final_triplestore_password: PASSWORD

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/pharmgkb


sparql_transform_queries_path: /data/mapping/pharmgkb/transform/1
sparql_insert_metadata_path: /data/mapping/pharmgkb/metadata/1