working_directory: /data/data2services-transform-biolink

dataset: hpo_annotations


# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: http://graphdb:7200
sparql_tmp_triplestore_repository: test
sparql_tmp_service_url: repository:test
sparql_tmp_triplestore_username: import_user
sparql_tmp_triplestore_password: PASSWORD

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/hpo_annotations"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
sparql_final_triplestore_url: http://graphdb:7200
sparql_final_triplestore_repository: "test"
sparql_final_triplestore_username: import_user
sparql_final_triplestore_password: PASSWORD

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/hpo_annotations

sparql_transform_queries_path: /data/mapping/hpo_annotations/transform/1
sparql_insert_metadata_path: /data/mapping/hpo_annotations/metadata/1
