working-directory: /data/d2s-transform-biolink

dataset: drugbank-sample

# d2s-download params
download-username: vincent.emonet@maastrichtuniversity.nl
download-password: maasitest12

# tmp RDF4J server SPARQL endpoint to load generic RDF
#sparql-tmp-triplestore-url: http://graphdb:7200
sparql-tmp-triplestore-url: http://node000002.cluster.ids.unimaas.nl/
sparql-tmp-triplestore-repository: "test"
sparql-tmp-service-url: "repository:test"
sparql-tmp-triplestore-username: import_user
sparql-tmp-triplestore-password: test

sparql-tmp-graph-uri: "https://w3id.org/data2services/graph/xml2rdf/drugbank"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
#sparql-final-triplestore-url: http://graphdb:7200
sparql-final-triplestore-url: http://node000002.cluster.ids.unimaas.nl/
sparql-final-triplestore-repository: "test"
sparql-final-triplestore-username: import_user
sparql-final-triplestore-password: test

sparql-final-graph-uri: https://w3id.org/data2services/graph/biolink/drugbank

sparql-transform-queries-path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/mapping/drugbank/transform/1
sparql-insert-metadata-path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/mapping/drugbank/metadata/1

# Argo require to use the URL
# sparql-transform-queries-path: /data/mapping/drugbank/transform/1






working_directory: /data/d2s-transform-biolink

dataset: drugbank-sample

# d2s-download params
download_username: my.drugbank.account@email.com
download_password: PASSWORD

# tmp RDF4J server SPARQL endpoint to load generic RDF
# By default linked on 'graphdb' docker container
sparql_tmp_triplestore_url: http://graphdb:7200
sparql_tmp_triplestore_repository: "test"
sparql_tmp_service_url: "repository:test"
sparql_tmp_triplestore_username: import_user
sparql_tmp_triplestore_password: PASSWORD

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/xml2rdf/drugbank"

# Final RDF4J server SPARQL endpoint to load the BioLink RDF
# By default linked on 'graphdb' docker container
sparql_final_triplestore_url: http://graphdb:7200
sparql_final_triplestore_repository: "test"
sparql_final_triplestore_username: import_user
sparql_final_triplestore_password: PASSWORD

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/drugbank

sparql_transform_queries_path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/mapping/drugbank/transform/1
sparql_insert_metadata_path: https://github.com/MaastrichtU-IDS/d2s-transform-biolink/tree/master/mapping/drugbank/metadata/1
