working_directory: /data/data2services-transform-biolink

#dataset: drugbank
dataset: pubmed

# d2s-download params
download_username: vincent.emonet@maastrichtuniversity.nl
download_password: PASSWORD

# xml2rdf params
sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/xml2rdf/pubmed"

# RdfUpload params
sparql_triplestore_url: http://graphdb:7200
sparql_triplestore_tmp_repository: test

# Execute SPARQL conversion queries
sparql_username: import_user
sparql_password: PASSWORD
sparql_output_graph_uri: https://w3id.org/data2services/graph/biolink/pubmed
sparql_service_url: "repository:test"

sparql_transform_queries_path: /data/mapping/pubmed/transform/1
sparql_insert_metadata_path: /data/mapping/pubmed/metadata/1

# Run workflow
# cwl-runner --outdir output/pubmed data2services-cwl-workflows/workflows/workflow-xml.cwl support/config/config-transform-xml-pubmed.yml