working_directory: /data/data2services-transform-biolink

#dataset: drugbank
dataset: drugbank-sample

# d2s-download params
download_username: vincent.emonet@maastrichtuniversity.nl
download_password: PASSWORD

# xml2rdf params
sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/xml2rdf/drugbank"

# RdfUpload params
sparql_triplestore_url: http://graphdb:7200
sparql_triplestore_tmp_repository: test
# sparql_triplestore_tmp_repository: test
# sparql_service_tmp_repository: repository:test

# sparql_triplestore_final_repository: ncats-red-kg

# Execute SPARQL conversion queries
sparql_username: import_user
sparql_password: PASSWORD
sparql_output_graph_uri: https://w3id.org/data2services/graph/biolink/drugbank
sparql_service_url: "http://localhost:7200/repositories/test"

sparql_transform_queries_path: /data/mapping/drugbank/transform/1
# Could be https://github.com/MaastrichtU-IDS/data2services-transform-repository/tree/master/sparql/insert-biolink/drugbank/
sparql_insert_metadata_path: /data/mapping/drugbank/metadata/1