PREFIX x2rm: <http://ids.unimaas.nl/xml2rdf/model#>
PREFIX x2rd: <http://ids.unimaas.nl/xml2rdf/data/>
PREFIX d2s: <https://w3id.org/data2services/vocab/>
PREFIX ido: <http://identifiers.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bl: <https://w3id.org/biolink/vocab/>
INSERT {
  GRAPH <?_outputGraph> {
    ?pubmedUri a bl:Publication ;
      bl:node_property ?KeywordValue .
      # No keyword property
  }
    .
} WHERE {
  SERVICE <?_serviceUrl>  {
    GRAPH <?_inputGraph> {

      # Get PMID
      ?medlineCitationObj x2rm:child:PMID [ x2rm:hasValue ?pmid ]
      BIND ( iri(concat("https://identifiers.org/pubmed:", ?pmid)) AS ?pubmedUri )

      ?medlineCitationObj x2rm:child:KeywordList [ x2rm:child:Keyword ?KeywordNode  ] .

      ?KeywordNode a x2rm:PubmedArticleSet.PubmedArticle.MedlineCitation.KeywordList.Keyword .

      OPTIONAL{ ?KeywordNode x2rm:hasValue ?KeywordValue . }

      OPTIONAL{ ?KeywordNode x2rm:attribute:MajorTopicYN ?MajorTopicYN . }
      # FILTER(?ValidYN = "Y")

    }
  }
}
