
input_dir:
  class: Directory
  path: /data/d2s-workspace/input/stitch

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: http://graphdb:7200/repositories/test/statements
sparql_tmp_service_url: "http://localhost:7200/repositories/test"
sparql_tmp_triplestore_username: import_user
sparql_tmp_triplestore_password: password

# sparql_tmp_triplestore_url: http://blazegraph:8889/bigdata/sparql

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/stitch"


# Final RDF4J server SPARQL endpoint to load the BioLink RDF
sparql_final_triplestore_url: http://graphdb:7200/repositories/test/statements
sparql_final_triplestore_username: import_user
sparql_final_triplestore_password: password

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/stitch

sparql_transform_queries_path: "mappings/1"
sparql_insert_metadata_path: "metadata/1"

cwl_workflow_filename: workflow-csv.cwl

config_dir:
  class: Directory
  path: .

cwl_dir:
  class: Directory
  path: ../../d2s-cwl-workflows