  PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
  PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
  PREFIX cito: <http://purl.org/spar/cito/>
  PREFIX dcat: <http://www.w3.org/ns/dcat#>
  PREFIX dctypes: <http://purl.org/dc/dcmitype/>
  PREFIX dct: <http://purl.org/dc/terms/>
  PREFIX foaf: <http://xmlns.com/foaf/0.1/>
  PREFIX freq: <http://purl.org/cld/freq/>
  PREFIX idot: <http://identifiers.org/idot/>
  PREFIX lexvo: <http://lexvo.org/ontology#>
  PREFIX pav: <http://purl.org/pav/>
  PREFIX prov: <http://www.w3.org/ns/prov#>
  PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  PREFIX schemaorg: <http://schema.org/>
  PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
  PREFIX sio: <http://semanticscience.org/resource/>
  PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
  PREFIX void: <http://rdfs.org/ns/void/>
  PREFIX void-ext: <http://ldf.fi/void-ext#>


INSERT {
	GRAPH <?_outputGraph/metadata> {

    <https://w3id.org/data2services/agent/hpo> a dct:Agent ;
      foaf:name "Human Phenotype Ontology Consortium" ;
      foaf:page <https://hpo.jax.org/> ;
      # sebastian.koehler@charite.de ?
    .

    # Summary
    <https://w3id.org/data2services/dataset/hpo_annotations>
      rdf:type dctypes:Dataset;
      dct:title "HPO annotations" ;
      idot:preferredPrefix "hpo_annotations" ;
      dct:description "This monthly job generates the data that is based on HPO-obo-file and the annotation-file. The generated data includes files that map genes to HPO-terms (and vice versa) and a SQL-dump of the MYSQL-database version of the HPO and its annotations."@en;
      dct:publisher <https://w3id.org/data2services/agent/hpo> ;
      
      dct:license <https://hpo.jax.org/app/license> ;
      #Human readable licenses terms
      dct:rights """All of the following license restrictions apply to all files provided by the HPO project:
      1. The HPO vocabularies, annotation files, tools and documentation are freely available.
      2. The HPO is copyrighted to protect the integrity of the vocabularies, which means that changes to the HPO vocabularies need to be done by HPO developers. However, anyone can download the HPO and use the ontologies or other HPO files under three conditions:
        - That the Human Phenotype Ontology Consortium is acknowledged and cited properly.
        - That any HPO Consortium file(s) displayed publicly include the date(s) and/or version number(s) of the relevant HPO file(s).
        - That neither the content of the HPO file(s) nor the logical relationships embedded within the HPO file(s) be altered in any way. (Content additions and modifications have to be suggested using our issue tracker.) 
      3. We suggest that you follow standard scientific citation practice if you use the HPO in publications.
      4. Users of the HPO should add the following statement to their online presence. This service/product uses the Human Phenotype Ontology (version information). Find out more at http://www.human-phenotype-ontology.org We request that the HPO logo be included as well. """@en ;

      foaf:page <https://hpo.jax.org/app/> ;
      schemaorg:logo <https://hpo.jax.org/app/assets/hpo-logo-white.png> ;
      dct:accrualPeriodicity freq:monthly ; # frequency of update

      # dcat:accessURL to specify a directory containing the file(s) of interest
      dcat:accessURL <http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/> ; 
      
      #void:sparqlEndpoint "http://graphdb.dumontierlab.com/repositories/ncats-red-kg" ;
      void:sparqlEndpoint "http://graphdb.dumontierlab.com/repositories/bio2vec" ;
      

      ## MAY
      # dcat:theme <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C48807> ;
      # dcat:keyword "genes" , "phenotypes" ;
      # dct:references <IRI> ; # Supporting material as web pages and documents (use cito for publications)
      # cito:citesAsAuthority <IRI> ; # publications about the dataset
      # rdfs:seeAlso <http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/> ;

      # dct:hasPart <IRI> ; # if the dataset has multiple different parts (e.g. one for Drugs, one for Phenotypes)
      # dct:alternative "Alternative label for dataset" ;
      # idot:alternatePrefix "alternative_prefix";


      ## Needs to be updated at new submission
      #pav:hasCurrentVersion <https://w3id.org/data2services/dataset/hpo_annotations/version/1> ;
    .
  }
} WHERE {
    BIND(NOW() AS ?now)
}
