PREFIX rr: <http://www.w3.org/ns/r2rml#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> 
PREFIX ql: <http://semweb.mmlab.be/ns/ql#> 
PREFIX d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> 
PREFIX pharmgkb_vocabulary: <http://bio2rdf.org/pharmgkb_vocabulary:> 

PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX freq: <http://purl.org/cld/freq/>
PREFIX idot: <http://identifiers.org/idot/>
PREFIX lexvo: <http://lexvo.org/ontology#>
PREFIX pav: <http://purl.org/pav/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schemaorg: <http://schema.org/>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX void-ext: <http://ldf.fi/void-ext#>

PREFIX bl: <http://bioentity.io/vocab/>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX hcls: <http://www.w3.org/hcls#>
PREFIX d2sdata: <http://data2services/data/>


INSERT {
	GRAPH <?_outputGraph/metadata> {

        <https://bio2rdf.org/bio2rdf_resource:data2services> a dct:Agent ;
            foaf:name "Data2Services Pipeline" ;
            foaf:page <https://github.com/MaastrichtU-IDS/data2services-pipeline> ;
        .

        # Summary
        <http:/bio2rdf.org/pharmgkb_resource:version/5>
            rdf:type dctypes:Dataset;
            dct:title "HPO annotations" ; 
            dct:description "Version 5 of PharmGKB generated by data2services";

            pav:version "5"^^xsd:string ; 
            dct:isVersionOf <http:/bio2rdf.org/lsr:pharmgkb> ;
     
			dcat:distribution <http://bio2rdf.org/sparql> ;
			dcat:distribution <http:/bio2rdf.org/pharmgkb_resource:version/5/rdf/data>;
            dcat:accessURL <https://bio2rdf.org/pharmgkb/version/5/index.html> ; 

            dct:license <https://opensource.org/licenses/MIT> ;
            dct:language <http://lexvo.org/id/iso639-3/eng>;
            
            dct:creator <https://github.com/MaastrichtU-IDS/data2services-pipeline> ;
            dct:issued  ?now;
            dct:publisher <https://github.com/MaastrichtU-IDS/data2services-pipeline> ;
		.
  
	 ### RDF Distribution description (Complete)
        <?_outputGraph>
            a dcat:Distribution, void:Dataset ;
            pav:version "156"^^xsd:string ; 
            dct:title "N-Quads distribution of HPO annotations monthly build #156" ;
            dct:description "N-Quads distribution of HPO annotations monthly build #156 produced by Data2Services on NOW()" ; 
            dct:license <http://creativecommons.org/licenses/by/3.0/> ; # TODO: What should be data2services BioLink RDF license?
            dct:conformsTo <http://www.w3.org/2001/sw/hcls/notes/hcls-dataset/> ;
			dct:source <http://bio2rdf.org/pharmgkb/source> ;
            dct:language <http://lexvo.org/id/iso639-3/eng> ; 
            void:vocabulary <http://bio2rdf.org/pharmgkb_vocabulary:> ; 

            dct:publisher <http://bio2rdf.org/> ; 
            dct:created '''NOW()''' ; 
            dct:creator <http://bio2rdf.org/bio2rdf_resource:data2services> ; 

            void:exampleResource <http://bio2rdf.org/pharmgkb:PA12345> ;

			dcat:mediaType "application/n-quads";
            dcat:accessURL <http://bio2rdf.org/pharmgkb/version/5/index.html> ;
            dcat:downloadURL <http://bio2rdf.org/pharmgkb/version/5/data/pharmgkb.nq.tgz> ; 
            void:dataDump <http://bio2rdf.org/pharmgkb/version/5/data/pharmgkb.nq.tgz> ;
		.
		        
        ### Distribution (non-RDF) description (Complete)
        <http://bio2rdf.org/pharmgkb/source>
            a dcat:Distribution ;
            dct:title "PharmGKB Database Distribution" ; # Must
            dct:description "The PharmGKB is a pharmacogenomics knowledge resource that encompasses clinical information including clinical guidelines and drug labels, potentially clinically actionable gene-drug associations and genotype-phenotype relationships." ; 
       
            dct:license <https://hpo.jax.org/app/license> ;
            dct:conformsTo <http://www.w3.org/2001/sw/hcls/notes/hcls-dataset/>;

            dct:publisher <http://www.pharmgkb.org> ;
            dct:creator <https://www.pharmgkb.org>; 
			pav:retrievedOn "datetime";
			
            dct:language <http://lexvo.org/id/iso639-3/eng>; 

            dct:format "text/tab-separated-values", "application/zip" ; 
            dcat:downloadURL <https://api.pharmgkb.org/v1/download/file/data> ;  
        .

       
    }
} WHERE {
    BIND(NOW() AS ?now)
}
