PREFIX d2smodel: <https://w3id.org/data2services/model/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX w3idvocab: <https://w3id.org/data2services/vocab/>
INSERT
{
  GRAPH <?_output> {  

    # https://biolink.github.io/biolink-model/docs/TranscriptToGeneRelationship.html
    ?refseqAssociationUri a bl:TranscriptToGeneRelationship ;
      bl:id ?refseqAssociationUriId ;
      bl:transcript_to_gene_relationship_subject ?RefseqAccessionUri ;
      bl:transcript_to_gene_relationship_object ?hgncUri ;
      bl:relation bl:expresses .
    # TODO: add evidence



    ?entity1 a ?entity1Type ;
      bl:id ?Entity1_id ;
      bl:name ?Entity1_name .

    ?entity2 a ?entity2Type ;
      bl:id ?Entity2_id ;
      bl:name ?Entity2_name .

 }
}
WHERE {
  SERVICE <?_service>  {
    GRAPH <?_input> {
      ?s d2smodel:Entity1_id ?Entity1_id ;
        d2smodel:Entity1_name ?Entity1_name ;
        d2smodel:Entity1_type ?Entity1_type ; # Can be gene, chemical, Haplotype
        d2smodel:Entity2_id ?Entity2_id ;
        d2smodel:Entity2_name ?Entity2_name ;
        d2smodel:Entity2_type ?Entity2_type ;
        d2smodel:Association ?Association . # Can be "not associated", "ambiguous" or "associated"

        FILTER(?Association = "associated") # Keep only associated entites. Should we take ambiguous?

        BIND ( iri(concat(?entity1BaseUri, ?Entity1_id) ) AS ?entity1 )
        BIND ( iri(concat(?entity2BaseUri, ?Entity2_id) ) AS ?entity2 )

        # Type: Haplotype, Variant, Chemical, Gene, Disease
        BIND ( iri(concat("http://w3id.org/biolink/", ?Entity1_type) ) AS ?entity1Type )
        BIND ( iri(concat("http://w3id.org/biolink/", ?Entity2_type) ) AS ?entity2Type )

        VALUES (?Entity1_type ?entity1BaseUri) {
          ( "Haplotype" <https://w3id.org/data2services/pharmgkb/> ) # no identifiers.org
          ( "Variant" <https://w3id.org/data2services/pharmgkb/> )
          ( "Chemical" <http://identifiers.org/pharmgkb.drug/> )
          ( "Gene" <http://identifiers.org/pharmgkb.gene/> )
          ( "Disease" <http://identifiers.org/pharmgkb.disease/> )
        }

        VALUES (?Entity2_type ?entity2BaseUri) {
          ( "Haplotype" <https://w3id.org/data2services/pharmgkb/> ) # no identifiers.org
          ( "Variant" <https://w3id.org/data2services/pharmgkb/> )
          ( "Chemical" <http://identifiers.org/pharmgkb.drug/> )
          ( "Gene" <http://identifiers.org/pharmgkb.gene/> )
          ( "Disease" <http://identifiers.org/pharmgkb.disease/> )
        }

       OPTIONAL { 
         ?s d2smodel:Evidence ?Evidence .
         #LabelAnnotation,Pathway,VariantAnnotation
         #Literature,MultilinkAnnotation,Pathway,VariantAnnotation

       } OPTIONAL { 
         ?s d2smodel:PK ?PK . # "PK" or nothing
       
       } OPTIONAL { 
         ?s d2smodel:PD ?PD . # "PD" or nothing
       
       } OPTIONAL { 
         ?s d2smodel:PMIDs ?PMIDs . # List of 15707415;22094953;23974086
       }
    }
  }
}