working_directory: /data/data2services-transform-biolink

dataset: hpo_annotations


# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"
sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/hpo_annotations"

# RdfUpload params
sparql_triplestore_url: http://graphdb:7200
sparql_triplestore_repository: test

# Execute SPARQL conversion queries
sparql_username: import_user
sparql_password: PASSWORD
sparql_output_graph_uri: https://w3id.org/data2services/graph/biolink/hpo_annotations
sparql_service_url: "http://localhost:7200/repositories/test"

sparql_transform_queries_path: /data/mapping/hpo_annotations/transform/1
sparql_insert_metadata_path: /data/mapping/hpo_annotations/metadata/1
