
dataset: eggnog

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"

# Split params
split_property: https://w3id.org/biolink/vocab/has_participant
split_class: https://w3id.org/biolink/vocab/GeneGrouping
split_delimiter: ","
split_quote: '"'

# tmp RDF4J server SPARQL endpoint to load generic RDF
sparql_tmp_triplestore_url: "http://virtuoso:8890/sparql"
sparql_tmp_service_url: "http://localhost:8890/sparql"
sparql_tmp_triplestore_username: dba
sparql_tmp_triplestore_password: dba

sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml"


# Final RDF4J server SPARQL endpoint to load the BioLink RDF
sparql_final_triplestore_url: "http://virtuoso:8890/sparql"
sparql_final_triplestore_username: dba
sparql_final_triplestore_password: dba

sparql_final_graph_uri: https://w3id.org/data2services/graph/biolink/eggnog


sparql_transform_queries_path: https://raw.githubusercontent.com/MaastrichtU-IDS/d2s-transform-template/master/datasets/eggnog/mappings/1/insert-eggnog.rq
sparql_insert_metadata_path: https://github.com/MaastrichtU-IDS/d2s-transform-template/tree/master/datasets/eggnog/metadata/1

cwl_workflow_filename: workflow-csv-split.cwl

config_dir:
  class: Directory
  path: .

cwl_dir:
  class: Directory
  path: ../../d2s-cwl-workflows