# This is a basic workflow to help you get started with Actions

name: Generate GeoNames RDF using RML

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: vemonet/rmlmapper-java@v4.8.0
      with:
        mapping: datasets/geonames/mapping/country_mapping.rml.ttl
        output: rdf_output.nq

    - name: Upload RDF output artifact
      uses: actions/upload-artifact@v1
      with:
        name: rdf_output
        path: rdf_output.nq
