name: EggNOG to BioLink RDF
# TODO: Add step to manage versioning (delete previous graph, load new graph, generate metadata)
on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: 'Upload to SPARQL endpoint'
        required: true
        default: 'https://graphdb.dumontierlab.com/repositories/ncats-red-kg/statements'
      graph:
        description: 'In the Graph'
        required: true
        default: 'https://w3id.org/d2s/graph/eggnog'
jobs:
  generate-rdf:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, X64, node2]
    outputs:
      rdf-output: ${{ steps.stepupload.outputs.rdf_output }}
    steps:
    - uses: actions/checkout@v2

    - name: Download CSV
      run: datasets/eggnog/download/download.sh

    - name: Run RML mapper
      uses: vemonet/rmlmapper-java@v4.9.0
      with:
        mapping: datasets/eggnog/mapping/map-eggnog.rml.ttl
        output: rdf-eggnog.nt
      env:
        JAVA_OPTS: "-Xmx6g"

    - name: Upload RDF output artifact
      id: stepupload
      uses: actions/upload-artifact@v1
      with:
        name: rdf-output
        path: rdf-eggnog.nt

  upload-rdf:
    runs-on: ubuntu-latest
    needs: generate-rdf
    steps:
    - uses: actions/checkout@v2

    - name: Get RDF output artifact
      uses: actions/download-artifact@v1
      with:
        name: rdf-output

    - name: Upload RDF
      uses: MaastrichtU-IDS/RdfUpload@master
      with:
        file: rdf-output/rdf-eggnog.nt
        endpoint: ${{ github.event.inputs.endpoint }}
        user: ${{ secrets.GRAPHDB_USER }}
        password: ${{ secrets.GRAPHDB_PASSWORD }}
        graph: ${{ github.event.inputs.graph }}

    - name: Compute and insert HCLS descriptive metadata
      uses: vemonet/sparql-operations-action@v1
      with:
        file: https://github.com/MaastrichtU-IDS/d2s-scripts-repository/tree/master/sparql/compute-hcls-stats
        endpoint: ${{ github.event.inputs.endpoint }}
        user: ${{ secrets.GRAPHDB_USER }}
        password: ${{ secrets.GRAPHDB_PASSWORD }}
        inputvar: ${{ github.event.inputs.graph }}
        outputvar: https://w3id.org/d2s/metadata
        servicevar: ${{ github.event.inputs.endpoint }}

    - name: Run RDF to HDT
      uses: vemonet/rdfhdt-action@master
      with:
        input: rdf-output/rdf-eggnog.nt
        output: hdt-eggnog.hdt

    - name: Upload HDT output artifact
      uses: actions/upload-artifact@v1
      with:
        name: hdt-output
        path: hdt-eggnog.hdt
