# This is a basic workflow to help you get started with Actions

name: Generate RML mappings from YARRRML

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  download-input:
    runs-on: ubuntu-latest
    steps: 
    - name: Download CSV
      run: |
        wget https://raw.githubusercontent.com/MaastrichtU-IDS/UM_KEN4256_KnowledgeGraphs/master/dataset-geonames-countryInfo.csv
    - name: Upload CSV input artifact
      uses: actions/upload-artifact@v1
      with:
        name: input
        path: dataset-geonames-countryInfo.csv

  generate-rdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get CSV input artifact
      uses: actions/download-artifact@v1
      with:
        name: input

    - uses: vemonet/rmlmapper-java@4.8
      with:
        input: datasets/geonames/mapping/split_neighbours_mapping.yarrr.yml
        output: datasets/geonames/mapping/split_neighbours_mapping.rml.ttl

    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Convert YARRRML mappings to RML'

    - name: Upload RML output artifact
      uses: actions/upload-artifact@v1
      with:
        name: rml_output
        path: datasets/geonames/mapping/split_neighbours_mapping.rml.ttl
