# This is a basic workflow to help you get started with Actions

name: Generate RML mappings from YARRRML

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  generate-rml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: vemonet/yarrrml-parser@v1.1
      with:
        input: datasets/geonames/mapping/split_neighbours_mapping.yarrr.yml
        output: datasets/geonames/mapping/split_neighbours_mapping.rml.ttl

    - name: Commit and push
      run: |
        git config --global user.name 'Vincent Emonet'
        git config --global user.email 'vincent.emonet@maastrichtuniversity.nl'
        git commit -am "Convert YARRRML mappings to RML"
        git push

    - name: Upload RML output artifact
      uses: actions/upload-artifact@v1
      with:
        name: rml_output
        path: datasets/geonames/mapping/split_neighbours_mapping.rml.ttl
