name: Generate RML mappings from YARRRML

on:
  push:
    branches: [ master ]
    paths:
    - 'datasets/geonames/mapping/split_neighbours_mapping.yarrr.yml'
    # Only run when change to YARRRML mapping file

jobs:

  generate-rml:
    runs-on: ubuntu-latest
    # TODO: Use outputs?

    steps:
    - uses: actions/checkout@v2

    - uses: vemonet/yarrrml-parser@v1.1
      with:
        input: datasets/geonames/mapping/split_neighbours_mapping.yarrr.yml
        output: datasets/geonames/mapping/split_neighbours_mapping.rml.ttl

    - name: Commit and push
      run: |
        git config --global user.name 'Vincent Emonet'
        git config --global user.email 'vincent.emonet@maastrichtuniversity.nl'
        git commit -am "Convert YARRRML mappings to RML"
        git push

    - name: Upload RML output artifact
      uses: actions/upload-artifact@v1
      with:
        name: rml_output
        path: datasets/geonames/mapping/split_neighbours_mapping.rml.ttl
